# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

on:
  push:
    paths:
     - 'github-actions/**'
  pull_request:
    paths:
     - 'github-actions/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: github-actions
        
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install uv
          if [ -f pyproject.toml ]; uv sync; fi

      - name: Rodar linters
        run: |
          pip install flake8
          flake8 . --count --max-line-length=88 --statistics

      - name: Rodar testes
        run: |
          pip install pytest
          pytest -v
        
