# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

on:
  push:
    branches: 'main'
    paths:
     - 'github-actions/**'
  pull_request:
    branches: 'main'
    paths:
     - 'github-actions/**'

jobs:
  build-and-tests:
    name: Build & Tests
    runs-on: ubuntu-latests

    defaults:
      run:
        working-directory: ./github-actions

    steps:
      - name: 1. Checkout do repositório
        uses: actions/checkout@v4

      - name: 2. Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      
      - name: 3. Cache de dependências do UV
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-
      
      - name: 4. Instalar dependências com UV
        run: |
          pip install uv
          uv sync
      
      - name: 5. Rodar Linter (Flake8) com UV
        run: uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: 6. Rodar Testes (Pytest) com UV
        run: uv run pytest -v
        
